class Maze_maps:

    maze_treasure = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP XXXXXXXT         X           X   TXXX",
    "X  XXXXXXX          XT          X    XXX",
    "X       XX  XXXXXX  XXXXXXXXX   XXX  XXX",
    "X       XX  XXX                      XXX",
    "XXXXXX  XX  XXXT       XXXXXXXXXXXXXXXXX",
    "XXXXXX  XX  XXXXXX     XXXXXXXXXXXXXXXXX",
    "XXXXXX  XX    XXXX      XX            XX",
    "XTXXXX        XXXX                    XX",
    "X  XXX                XXXX            TX",
    "X   XX       XXXXXXXXXXXXX            XX",
    "X    X   XX      XXT    XX  XXXXXXXXXXXX",
    "XXXX    XXXX     XX     XX          TXXX",
    "XXXXX  XXXXXX    XXXXX  X   XXXXXXXXXXXX",
    "XXXG XXXXXXXXX          X              X",
    "XXX                     XX  XXXXXXXXX  X",
    "XXX            XXXXXXXXXXXX  XXXXXXX  XX",
    "XXXXXXXXXX     XXX      XXXX  XXXXX  XXX",
    "XXXXXXXXXX                XXX  XXX  XXXX",
    "XXT  XXXXX                 TXX  X  XXXXX",
    "XX   XXXXXXXX             XXX  XXX  XXXX",
    "XX    XXXXXXX  XXX      XXXX  XXXXX  XXX",
    "XX             XXXXXXXXXXXX  XXXXXXX  XX",
    "XXXX   T                XX TXXXXXXXXXT X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

    maze_easy = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP XXXXXXX          XXXXX",
    "X  XXXXXXX  XXXXXX  XXXXX",
    "X       XX  XXXXXX  XXXXX",
    "X       XX  XXX        XX",
    "XXXXXX  XX  XXX        XX",
    "XXXXXX  XX  XXXXXX  XXXXX",
    "XXXXXX  XX    XXXX  XXXXX",
    "X  XXX        XXXXG XXXXX",
    "X  XXX  XXXXXXXXXXXXXXXXX",
    "X         XXXXXXXXXXXXXXX",
    "X                XXXXXXXX",
    "XXXXXXXXXXXX     XXXXX  X",
    "XXXXXXXXXXXXXXX  XXXXX  X",
    "XXX  XXXXXXXXXX         X",
    "XXX                     X",
    "XXX         XXXXXXXXXXXXX",
    "XXXXXXXXXX  XXXXXXXXXXXXX",
    "XXXXXXXXXX              X",
    "XX   XXXXX              X",
    "XX   XXXXXXXXXXXXX  XXXXX",
    "XX    XXXXXXXXXXXX  XXXXX",
    "XX          XXXX        X",
    "XXXX                    X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
]