class Maze_maps:

    maze_treasure = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP XXXXXXXT        TXT          XT   XXX",
    "X  XXXXXXX          X           X    XXX",
    "X       XX  XXXXXX  XXXXXXXXX   XXX  XXX",
    "L       XX  XXX                      XXX",
    "XXXXXX  XX  XXX        XXXXXXXXXXXXXXXXX",
    "XXXXXX  XX  XXXXXX     XXXXXXXXXXXXXXXXX",
    "XXXXXX  XX    XXXX      XX            XX",
    "XTXXXX        XXXX                    XX",
    "X  XXX                XXXX            TX",
    "X   XX       XXXXXXXXXXXXX            XX",
    "X    X   XX      XX     XX  XXXXXXXXXXXX",
    "XXXX    XXXX     XX     XX          TXXX",
    "XXXXXT XXXXXX    XXXXX  X   XXXXXXXXXXXX",
    "XXXG XXXXXXXXX          X              X",
    "XXX                     XX  XXXXXXXXX  X",
    "XXX            XXXXXXXXXXXX  XXXXXXX  XX",
    "XXXXXXXXXX     XXX      XXXX  XXXXX  XXX",
    "XXXXXXXXXX                XXX  XXX  XXXX",
    "XXT  XXXXXT                TXX  X  XXXXX",
    "XX   XXXXXXXX             XXX  XXX  XXXX",
    "XX    XXXXXXX  XXX      XXXX  XXXXX  XXX",
    "XX             XXXXXXXXXXXX  XXXXXXX  XX",
    "XXXX                   TXXT XXXXXXXXX TX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    ]

    maze_easy = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP XXXXXXX          XXXXX",
    "X  XXXXXXX  XXXXXX  XXXXX",
    "X       XX  XXXXXX  XXXXX",
    "L       XX  XXX        XX",
    "XXXXXX  XX  XXX        XX",
    "XXXXXX  XX  XXXXXX  XXXXX",
    "XXXXXX  XX    XXXX  XXXXX",
    "X  XXX        XXXXG XXXXX",
    "X  XXX  XXXXXXXXXXXXXXXXX",
    "X         XXXXXXXXXXXXXXX",
    "X                XXXXXXXX",
    "XXXXXXXXXXXX     XXXXX  X",
    "XXXXXXXXXXXXXXX  XXXXX  X",
    "XXX  XXXXXXXXXX         X",
    "XXX                     X",
    "XXX         XXXXXXXXXXXXX",
    "XXXXXXXXXX  XXXXXXXXXXXXX",
    "XXXXXXXXXX              X",
    "XX   XXXXX              X",
    "XX   XXXXXXXXXXXXX  XXXXX",
    "XX    XXXXXXXXXXXX  XXXXX",
    "XX          XXXX        X",
    "XXXX                    X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
    ]


    maze_treasure2 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "P      XXXXXXXX      T             T   X",
    "X     XXT     XX     XX           XX   X",
    "X    XX        XX    XX           XX   X",
    "X   XX         XX    XX           XX   X",
    "X  XX          XX    XX           XX   X",
    "X XX                 XX           XX   X",
    "X XX           T     XXT         TXX   X",
    "X XX       XXXXXXXX  XXXXXXXXXXXXXXX   X",
    "X XX        XXXXXX   XXXXXXXXXXXXXXX   X",
    "X XX         XXXX     XXT        TXX   X",
    "X  XX         XX     X  X         XX   X",
    "X   XX       TXX    X  X          XX   X",
    "X    XXXXXXXXXX    X  X           XX   X",
    "L                 X  X            XX   X",
    "X   XXXXXXXXXXXXXX  XXXXXXXXXX    XX   X",
    "X                             XT  XX   X",
    "X                XXXXXXXXXXXXX         X",
    "X                             XT       X",
    "X                XXXXXXXXXXXXX         X",
    "X                             XT       X",
    "X                XXXXXXXXXXXXX         X",
    "X                             XT       X",
    "X   XXXXXXXXXXXXXXXXXXXXXXXXXX         X",
    "X                                      X",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    ]

    maze_easy2 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "P                       L",
    "XXXXXXXXXXXX XXXXXXXXXXXX",
    "X                       X",
    "X   XXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXX   X",
    "X                       X",
    "X   XXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXX   X",
    "X                       X",
    "X   XXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXX   X",
    "X                       X",
    "X   XXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXX   X",
    "X                       X",
    "X   XXXXXXXXXXXXXXXXXXXXX",
    "X                       X",
    "XXXXXXXXXXXXXXXXXXXXX   X",
    "G                       X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX"
    ]

    maze_medium = [
    "                                                    ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    " XP                     LX         X         X    X ",
    " XXXXXXXXXXX XXXXXXXXXXXXX         X         X    X ",
    " X                       X    X    X    X    X    X ",
    " X   XXXXXXXXXXXXXXXXXXXXX    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " XXXXXXXXXXXXXXXXXXXXX   X    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " X   XXXXXXXXXXXXXXXXXXXXX    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " XXXXXXXXXXXXXXXXXXXXX   X    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " X   XXXXXXXXXXXXXXXXXXXXX    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " XXXXXXXXXXXXXXXXXXXXX   X    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " X   XXXXXXXXXXXXXXXXXXXXX    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " XXXXXXXXXXXXXXXXXXXXX   X    X    X    X    X    X ",
    " X                       X    X    X    X    X    X ",
    " X   XXXXXXXXXXXXXXXXXXXXX    X         X         X ",
    " X                            X         X         X ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X ",
    " G                                                X ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "                                                    "
    ]


    maze_medium2 = [
    "                                                    ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    " XP                      X         X         X   LX ",
    " X     XXXXXXXXXXXXXXX   X         X              X ",
    " X      X      X  X      X    X    X    XX   X    X ",
    " X      X  X   X  X    XXX    XXXX X    XX   X    X ",
    " X         X      X      XXX  X    X   XX    X    X ",
    " X     XXXXXXXXXXXXXXXXXXX    X    X   XX    X    X ",
    " X                            X   X X   X         X ",
    " X   XXXXXXXXXXXXXXXXXXXXX    X  X   X  XX   XX   X ",
    " X         X  X          X    X         XX   XX   X ",
    " X    X    X  X    X          X    X    X   XX    X ",
    " X    X       X    X     X    X    X    X   XX  XXX ",
    " X   XXXXXXXX X  XXXXXXXXXXX  X         X         X ",
    " X                       X    X  X   X  XXX XX    X ",
    " XXX  XXX   XXXX    XXX  X    X   X X   X    X    X ",
    " X   XX    XXXXXX     XX X  XXX    X    X    X    X ",
    " X  XXXXXXXXXXXXXXXXXXXXXX    X    X    XXX  X    X ",
    " X   XX     XXXX      XX      X    X         X    X ",
    " XXX  XXX    XX     XXX  X    X    X    X    X    X ",
    " X                       XXXXXXXXX X XXXXXXXXX    X ",
    " X   XXXXXXXXXXXXXXXXXXXXX            X           X ",
    " X  X                         X         X         X ",
    " XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X ",
    " G                                            X   X ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "                                                    "
    ]

    maze_hard = [
    "                                                    ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    " XP    LXXX     XXXX   XXXXXX         X    XXXX   X ",
    " X     X  X    X    X X      X       X     X   X  X ",
    " X        X   X         X     X     X   X     X   X ",
    " X        X    XX  XXXXXX      X         X X   X  X ",
    " X        X   X      X  XXX    X  XXXXXXXXXX XX   X ",
    " X     XXXXXXX      X  X      X  X         X   XXXX ",
    " X    XXXXX     XXXX    X       X   XXXXXXX X     X ",
    " X   X     X  XXXXXXXXX XXXXXXXX       X     X    X ",
    " X   X    X          X      XXXXXXXXXX X   XX XXX X ",
    " X       X          X       X X        X   XX     X ",
    " X      X          X  X     XX    X    X   X  X   X ",
    " X     X          X   X     X X   XXXX X XXX  X   X ",
    " X XX XXXXXXXXXX X    X     X  X  X  X   X X XXXXXX ",
    " X  X XX    X    XXX  XXXXX X   X X  XXX X X      X ",
    " X X    X   X      X   X  X       X  X   X XXXXX  X ",
    " X X     X   XXXX  X X  X  X     X   X   X XXXXX  X ",
    " X     XX        X XX   XXX XXXXX     X X  X      X ",
    " X          X    X X   X   X         X   X X XXXXXX ",
    " X X     XXXX XXX  XX  X X  X XXXX  X     XX      X ",
    " XXX    X   X      X X    X X X  X  X             X ",
    " X  XXXX    XX     X  XX  X   X  X  X  XXX XXXXXX X ",
    " X   XX   X   XXXXX    X    X  X X   X   X X      X ",
    " G      X   X        X    X   X       XXXX X      X ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "                                                    "
    ]

    maze_hard2 = [
    "                                                    ",   
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    " P             XXXXXX  XXXXXXXXXXXXXXXXXXX        G ",
    " X           XX      XX XXXXXXXXX XX     XX       X ",
    " X          XX        XX   X X    XX      XX      X ",
    " X          XX        XX   X X    XX       XX     X ",
    " XXXXXXXXXX  XX      XX    X X    XX       XX     X ",
    " X       XX    XXXXXX      X X    XX XXXXXXX      X ",
    " X                                XX XXXXXXX      X ",
    " XXXXX   XX      XXXXX      XXX   XX       XX     X ",
    " X   X   XX    XX     XX  XX   XX XX        XX    X ",
    " X       XX   XX       X  X XXX   XX        XX    X ",
    " X XX    XX    XX     XX        XXXX       XX     X ",
    " X X     XX      XXXXX     XX  XX XXXXXXXXXX      X ",
    " X X     XXXXXXXXXX        XX XX   X   XX  X      X ",
    " X  X     XX        XX     XX X    X  X  X X      X ",
    " X         XX      XX      XX XX   X  X  X X      X ",
    " XXXXXX     XX    XX   XX  XX  XX  XXX XX  XXXXXXXX ",
    " X    X      XX  XX    XX XXX   XX                X ",
    " XXX      X   X  X     XX XX  X     XX   XXXXX    X ",
    " XXX  XX X X  X  X      L  XX X     X X  X        X ",
    " X        X XXX  XX    XX   XXX     X  X XXX      X ",
    " XXXXx X    XX    XX   XX  XX X     X   XXXX      X ",
    " X          X     X    XX  X        X  X X        X ",
    " X        X         XX XXX     XXXXX X   XXXXX      ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "                                                    "
    ]

    maze_multi = [
    " P                                                L ",   
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ",
    "                          X                         ",
    " XXXXXXXXXXXXXXXXXXXXXX   X   XXXXXXXXXXXXXXXXXXXXX ",
    " X                        X                       X ",
    " X   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X ",
    " X                        X                       X ",
    " XXXXXXXXXXXXXXXXXXXXXX   X   XXXXXXXXXXXXXXXXXXXXX ",
    " X                        X                       X ",
    " X   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X ",
    " X                        X                       X ",
    " XXXXXXXXXXXXXXXXXXXXXX   X   XXXXXXXXXXXXXXXXXXXXX ",
    " X                        X                       X ",
    " X   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X ",
    " X                     X  G  X                    X ",
    " XXXXXXXXXXXXXXXXXXX   X  X  X   XXXXXXXXXXXXXXXXXX ",
    " X                     X  X  X                    X ",
    " X   XXXXXXXXXXXXXXXXXXX  X  XXXXXXXXXXXXXXXXXX   X ",
    " X                     X  X  X                    X ",
    " XXXXXXXXXXXXXXXX  XXXXX  X  XXXXX  XXXXXXXXXXXXXXX ",
    " X                     X  X  X                    X ",
    " X  XXXXXXXXXXXXXXXXXXXX  X  XXXXXXXXXXXXXXXXXXX  X ",
    " X                     X  X  X                    X ",
    " XXXXXXXXXXXXXXXXX  XXXX  X  XXXX  XXXXXXXXXXXXXXXX ",
    " X                        X                       X ",
    " XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX ",
    "                                                    "
    ]